-- Sprint 2 Snowflake Setup - COPY INTO RAW Tables
-- Purpose: Load raw retail CSV files from the Azure external stage into Snowflake RAW tables.
-- Source: Snowflake query history COPY INTO statements.
-- Grain: One COPY command per raw source CSV file.
-- Known limitations: Raw CSV files remain in Azure Blob Storage and are not committed to GitHub.

COPY INTO RAW_CUSTOMERS
FROM @AZURE_RAW_STAGE/raw_customers.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

COPY INTO RAW_ORDERS
FROM @AZURE_RAW_STAGE/raw_orders.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

COPY INTO RAW_ORDER_ITEMS
FROM @AZURE_RAW_STAGE/raw_order_items.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

COPY INTO RETAIL_MLOPS.RAW.RAW_PRODUCTS
FROM @RETAIL_MLOPS.RAW.AZURE_RAW_STAGE/raw_products.csv
FILE_FORMAT = RETAIL_MLOPS.RAW.CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RETAIL_MLOPS.RAW.RAW_STORES
FROM @RETAIL_MLOPS.RAW.AZURE_RAW_STAGE/raw_stores.csv
FILE_FORMAT = RETAIL_MLOPS.RAW.CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RETAIL_MLOPS.RAW.RAW_SUPPLIES
FROM @RETAIL_MLOPS.RAW.AZURE_RAW_STAGE/raw_supplies.csv
FILE_FORMAT = RETAIL_MLOPS.RAW.CSV_FORMAT
ON_ERROR = 'ABORT_STATEMENT';
